services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    depends_on:
      firebase-emulator:
        condition: service_healthy
    

  firebase-emulator:
    build:
      context: ./firebase
    working_dir: "/firebase"
    volumes:
      - .cache/firebase/emulators/:/app/.cache/firebase/emulators/ 
      - ./firebase:/firebase
      - firebase_data:/firebase/data
    ports:
      - "4000:4000" # Firebase Emulator UI
      - "8080:8080" # Firestore 
      - "9000:9000" # Database
      - "9099:9099" # Authentication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  firebase_data: