name: Run Tests

on: [push, pull_request] # Run on push and pull_request events

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./api

    - name: Run tests
      run: go test ./... -v
      working-directory: ./api